# Generated by Django 4.2 on 2023-12-16 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='poem_images')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.genre')),
            ],
        ),
    ]
